orders = [
    {
        "order_id": "001",
        "city": "São Paulo",
        "delivery_cost": 450.00,
        "days_late": 3,
        "status": "delivered",
        "freight": 45.00,
        "order_value": 890.00,
    },
    {
        "order_id": "002",
        "city": "Rio de Janeiro",
        "delivery_cost": 320.00,
        "days_late": 0,
        "status": "delivered",
        "freight": 32.00,
        "order_value": 560.00,
    },
    {
        "order_id": "003",
        "city": "Monterrey",
        "delivery_cost": 210.00,
        "days_late": -2,
        "status": "delivered",
        "freight": 21.00,
        "order_value": 340.00,
    },
    {
        "order_id": "004",
        "city": "Guadalajara",
        "delivery_cost": 780.00,
        "days_late": 7,
        "status": "delivered",
        "freight": 78.00,
        "order_value": 1200.00,
    },
    {
        "order_id": "005",
        "city": "Belo Horizonte",
        "delivery_cost": 95.00,
        "days_late": 1,
        "status": "cancelled",
        "freight": 0.00,
        "order_value": 0.00,
    },
    {
        "order_id": "006",
        "city": "Salvador",
        "delivery_cost": 540.00,
        "days_late": -1,
        "status": "delivered",
        "freight": 54.00,
        "order_value": 670.00,
    },
    {
        "order_id": "007",
        "city": "Fortaleza",
        "delivery_cost": 0.00,
        "days_late": 12,
        "status": "delivered",
        "freight": 0.00,
        "order_value": 430.00,
    },
    {
        "order_id": "008",
        "city": "Curitiba",
        "delivery_cost": 380.00,
        "days_late": 0,
        "status": "delivered",
        "freight": 38.00,
        "order_value": 920.00,
    },
    {
        "order_id": "009",
        "city": "Manaus",
        "delivery_cost": 1200.00,
        "days_late": 5,
        "status": "delivered",
        "freight": 120.00,
        "order_value": 2100.00,
    },
    {
        "order_id": "010",
        "city": "São Paulo",
        "delivery_cost": 310.00,
        "days_late": -3,
        "status": "delivered",
        "freight": 31.00,
        "order_value": 480.00,
    },
    {
        "order_id": "011",
        "city": "Rio de Janeiro",
        "delivery_cost": 0.00,
        "days_late": 2,
        "status": "cancelled",
        "freight": 0.00,
        "order_value": 0.00,
    },
    {
        "order_id": "012",
        "city": "Recife",
        "delivery_cost": 670.00,
        "days_late": 9,
        "status": "delivered",
        "freight": 67.00,
        "order_value": 1500.00,
    },
    {
        "order_id": "013",
        "city": "Porto Alegre",
        "delivery_cost": 420.00,
        "days_late": 0,
        "status": "delivered",
        "freight": 42.00,
        "order_value": 780.00,
    },
    {
        "order_id": "014",
        "city": "Manaus",
        "delivery_cost": 950.00,
        "days_late": 14,
        "status": "delivered",
        "freight": 95.00,
        "order_value": 1800.00,
    },
    {
        "order_id": "015",
        "city": "Fortaleza",
        "delivery_cost": 280.00,
        "days_late": -1,
        "status": "delivered",
        "freight": 28.00,
        "order_value": 390.00,
    },
]


# for order in orders:
#     if order["status"] == "delivered" and order["days_late"] > 0:
#         print(
#             "delivered and is Late",
#             order["city"],
#             order["order_id"],
#             order["delivery_cost"],
#         )

total = 0
for order in orders:
    total = total + order["delivery_cost"]
print(total / len(orders))
